auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:categories/:title

title:            BeiYuu.com
url:              http://beiyuu.com
feed:             /atom.xml
author:
    name:         GuoJing
    twitter:      twitter.com/guojing
description:      "GuoJing\'s Blog"