auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         1
permalink:        /:categories/:year/:month/:day/:title/

title:            "Vanto's Blog"
url:              http://vanto.tk
feed:             /feed.xml
author:
    name:         Vanto
    twitter:      
    key:          vanto
description:      "只要心还跳"
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "Vanto的博客，关于技术、生活。"
headkeys:         "设计,开发,思考,生活,豆瓣,读书,电影,音乐,游记"
