auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         10
permalink:        /:categories/:year/:month/:day/:title/

title:            guojing.me
url:              http://guojing.me
feed:             /feed.xml
author:
    name:         GuoJing
    twitter:      twitter.com/guojing
description:      "GuoJing\'s Blog"
copyright:        "CopryRight guojing 2012-2012"