auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         10
permalink:        /:categories/:year/:month/:day/:title/

title:            "GuoJing's Blog"
url:              http://guojing.me
feed:             /feed.xml
author:
    name:         GuoJing
    twitter:      twitter.com/guojing
description:      "只要心还跳"
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"