auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            jguoer.com
url:              http://jguoer.com
feed:             /atom.xml
author:
    name:         GuoJing
    twitter:      twitter.com/guojing
description:      "GuoJing\'s Blog"